version: "3"
services:
  discovery:
    container_name: eureka-docker
    image: eureka-docker
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - rentific

  authentication-service:
    image: authentication-docker
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    container_name: authentication-docker
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    expose:
      - 8090
    ports:
      - 8090:8090
    restart: on-failure
    links:
      - discovery:eureka-docker
    depends_on:
      - discovery
      - userservice
      - api-gateway
    networks:
      - rentific

  api-gateway:
    image: gateway-docker
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SECURITY_OAUTH2_RESOURCE_GETTOKEN: http://authentication-service:8090/oauth/token
      SECURITY_OAUTH2_RESOURCE_ACCESSTOKENURI: http://authentication-service:8090/oauth/access_token
      SECURITY_OAUTH2_RESOURCE_TOKEN-INFO-URI: http://authentication-service:8090/oauth/check_token
      SECURITY_OAUTH2_RESOURCE_USER-INFO-URI: http://authentication-service:8090/user
      SECURITY_OAUTH2_RESOURCE_USERAUTHORIZATIONURI: http://authentication-service:8090/oauth/authorize
    container_name: gateway-docker
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    expose:
      - 8762
    ports:
      - 8762:8762
    restart: on-failure
    links:
      - discovery:eureka-docker
    depends_on:
      - discovery
      - userservice
    networks:
      - rentific

  #mysql konekcije
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: db_user
      MYSQL_ROOT_USER: root
      MYSQL_USER: sanida
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_PORT: 3306
      MYSQL_HOST: 172.18.0.4
      MYSQL_ROOT_HOST: localhost
    ports:
    - 3306:3306
    networks:
      - rentific

  userservice:
    image: user-docker
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: sanida
      DATABASE_PASSWORD: test123
      DATABASE_NAME: db_user
      DATABASE_PORT: 3306
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/db_user?useSSL=false&allowPublicKeyRetrieval=true'
    container_name: user-docker
    build:
      context: ./userservice
      dockerfile: Dockerfile
    expose:
      - 8082
    ports:
      - 8082:8082
    networks:
      - rentific
    restart: on-failure
    links:
      - discovery:eureka-docker
      - mysql:mysql
    depends_on:
      - mysql
      - discovery


networks:
  rentific:
    driver: bridge
