version: "3"
services:
  discovery:
    container_name: eureka-docker
    image: eureka-docker
    restart: always
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    expose:
      - 8761
    ports:
      - 8761:8761
    networks:
      - rentific

  rentific-frontend:
    container_name: rentific-container
    build:
      context: ./RentificApp
      dockerfile: Dockerfile
    image: rentific-frontend
    restart: always
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - rentific

  authentication-service:
    image: authentication-docker
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    container_name: authentication-docker
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    expose:
      - 8090
    ports:
      - 8090:8090
    restart: on-failure
    links:
      - discovery:eureka-docker
    depends_on:
      - discovery
      - userservice
      - api-gateway
    networks:
      - rentific

  api-gateway:
    image: gateway-docker
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SECURITY_OAUTH2_RESOURCE_GETTOKEN: http://authentication-service:8090/oauth/token
      SECURITY_OAUTH2_RESOURCE_ACCESSTOKENURI: http://authentication-service:8090/oauth/access_token
      SECURITY_OAUTH2_RESOURCE_TOKEN-INFO-URI: http://authentication-service:8090/oauth/check_token
      SECURITY_OAUTH2_RESOURCE_USER-INFO-URI: http://authentication-service:8090/user
      SECURITY_OAUTH2_RESOURCE_USERAUTHORIZATIONURI: http://authentication-service:8090/oauth/authorize
    container_name: gateway-docker
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    expose:
      - 8762
    ports:
      - 8762:8762
    restart: on-failure
    links:
      - discovery:eureka-docker
    depends_on:
      - discovery
      - userservice
    networks:
      - rentific

  #mysql konekcije
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: db_user
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_PORT: 3306
    ports:
    - 3306:3306
    networks:
      - rentific

  userservice:
    image: user-docker
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: root
      DATABASE_PASSWORD: test123
      DATABASE_NAME: db_user
      DATABASE_PORT: 3306
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/db_user?useSSL=false&allowPublicKeyRetrieval=true'
    container_name: user-docker
    build:
      context: ./userservice
      dockerfile: Dockerfile
    expose:
      - 8082
    ports:
      - 8082:8082
    networks:
      - rentific
    restart: on-failure
    links:
      - discovery:eureka-docker
      - mysql:mysql
    depends_on:
      - mysql
      - discovery


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rentific

  #mysql konekcije
  mysql-rent:
    image: mysql:8.0.16
    container_name: mysql-rent
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: db_reservation
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test123
    networks:
        - rentific

  rent:
    image: rent-docker
    environment:
      DATABASE_HOST: mysql-rent
      DATABASE_PASSWORD: test123
      DATABASE_NAME: db_reservation
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-rent:3306/db_reservation?useSSL=false&allowPublicKeyRetrieval=true'
      SPRING_RABBITMQ_HOST: rabbitmq
      container_name: rent-docker
    build:
      context: ./rentservice
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - rentific
    restart: on-failure
    links:
      - discovery:eureka-docker
      - mysql-rent:mysql-rent
      - rabbitmq:rabbitmq
    depends_on:
      - mysql-rent
      - discovery
      - rabbitmq

  mysql-invoice:
    image: mysql:8.0.16
    container_name: mysql-invoice
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: db_invoice
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test123
    networks:
      - rentific

  invoice:
    image: invoice-docker
    environment:
      DATABASE_HOST: mysql-invoice
      DATABASE_PASSWORD: test123
      DATABASE_NAME: db_invoices
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-invoice:3306/db_reservation?useSSL=false&allowPublicKeyRetrieval=true'
      SPRING_RABBITMQ_HOST: rabbitmq
      container_name: invoice-docker
    build:
      context: ./invoiceservice (1)/invoiceservice
      dockerfile: Dockerfile
    expose:
      - 8081
    ports:
      - 8081:8081
    networks:
      - rentific
    restart: on-failure
    links:
      - discovery:eureka-docker
      - mysql-invoice:mysql-invoice
      - rabbitmq:rabbitmq
    depends_on:
      - mysql-invoice
      - discovery
      - rabbitmq

  mysql-admin:
    image: mysql:8.0.16
    container_name: mysql-admin
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_DATABASE: db_admin
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: test123
    networks:
      - rentific

  admin:
    image: admin-docker
    environment:
      DATABASE_HOST: mysql-admin
      DATABASE_PASSWORD: test123
      DATABASE_NAME: db_admin
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-admin:3306/db_reservation?useSSL=false&allowPublicKeyRetrieval=true'
      SPRING_RABBITMQ_HOST: rabbitmq
      container_name: admin-docker
    build:
      context: ./adminservice/adminservice
      dockerfile: Dockerfile
    expose:
      - 8083
    ports:
      - 8083:8083
    networks:
      - rentific
    restart: on-failure
    links:
      - discovery:eureka-docker
      - mysql-admin:mysql-admin
      - rabbitmq:rabbitmq
    depends_on:
      - mysql-admin
      - discovery
      - rabbitmq

networks:
  rentific:
    driver: bridge
