package com.example.rentservice.rentservice.Controllers;

import com.example.rentservice.rentservice.Models.RealEstate;
import com.example.rentservice.rentservice.Models.State;
import com.example.rentservice.rentservice.Models.User;
import com.example.rentservice.rentservice.Repositories.RealEstateRepository;
import com.example.rentservice.rentservice.Repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.Date;

@Controller // This means that this class is a Controller
@RequestMapping(path="/realEstate") // This means URL's start with /demo (after Application path)
public class RealEstateController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RealEstateRepository realEstateRepository;

    @PostMapping(path="/add")
    public @ResponseBody RealEstate add (@RequestBody RealEstate realEstate) {
        return realEstateRepository.save(realEstate);
    }
    @GetMapping(path="/all")
    public @ResponseBody Iterable<RealEstate> getAllRealEstates() {
        // This returns a JSON or XML with the users
        return realEstateRepository.findAll();
    }
}